---
extends: default

rules:
  document-start:
    present: true
  indentation:
    spaces: 2
  key-ordering:
    enable: true  # Enforce alphabetized keys, per project instructions
  line-length:
    max: 80
  empty-lines:
    max: 1