---
extends: default

ignore:
  - .venv/
  - .github/

rules:
  document-start:
    present: true
  empty-lines:
    max: 1
  indentation:
    spaces: 2
  key-ordering: enable
  line-length:
    max: 120
  truthy: disable
