# Traefik dynamic configuration
http:
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: /run/secrets/traefik_dashboard_users
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true