---
# Validates Docker Compose configuration
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Validate Docker Compose file
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose -f docker-compose.yml config
          else
            echo "docker-compose.yml not found, skipping validation."
          fi

name: Validate Docker Compose

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
