# Validates YAML files and checks for formatting issues
name: Lint YAML Files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Check if YAML files exist
        id: check_yaml
        run: |
          if find . -type f \( -name "*.yml" -o -name "*.yaml" \) | grep -q .; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run yamllint
        if: steps.check_yaml.outputs.exists == 'true'
        run: yamllint -c .yamllint.yml .